id: ACA0CFB4E
title: 1. Nidāna
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:49:46.521064
  last_modified_at: 2022-03-01 21:49:46.521073
