id: ACA0CFB4E
title: 14. Bodhisattvapṛthivīvirasamudgama
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:49:46.644003
  last_modified_at: 2022-03-01 21:49:46.644010
