id: ACA0CFB4E
title: 26. Samantabhadrotsāhana
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:49:46.811289
  last_modified_at: 2022-03-01 21:49:46.811292
