id: ACA0CFB4E
title: 9. Ānandādivyākaraṇa
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:49:47.011299
  last_modified_at: 2022-03-01 21:49:47.011304
