id: ACA0CFB4E
title: 19. Sadāparibhūta
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:49:46.709819
  last_modified_at: 2022-03-01 21:49:46.709823
