id: ACA0CFB4E
title: 21. Dhāraṇī
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:49:46.778388
  last_modified_at: 2022-03-01 21:49:46.778391
