id: ACA0CFB4E
title: 25. Śubhavyūharājapūrvayoga
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:49:46.807493
  last_modified_at: 2022-03-01 21:49:46.807496
